// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// p_gradUsparse
void p_gradUsparse(NumericMatrix Xm, NumericMatrix Gm, NumericMatrix CUm, NumericMatrix OUm, NumericMatrix Cm, NumericVector I, NumericVector T, NumericVector Rowm, NumericVector Colm);
RcppExport SEXP CMF_p_gradUsparse(SEXP XmSEXP, SEXP GmSEXP, SEXP CUmSEXP, SEXP OUmSEXP, SEXP CmSEXP, SEXP ISEXP, SEXP TSEXP, SEXP RowmSEXP, SEXP ColmSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xm(XmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type Gm(GmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type CUm(CUmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type OUm(OUmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type Cm(CmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type I(ISEXP );
        Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Rowm(RowmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Colm(ColmSEXP );
        p_gradUsparse(Xm, Gm, CUm, OUm, Cm, I, T, Rowm, Colm);
    }
    return R_NilValue;
END_RCPP
}
// p_updatePseudoData
void p_updatePseudoData(NumericMatrix Xm, NumericMatrix U1m, NumericMatrix U2m, NumericVector Rv, NumericVector Cv);
RcppExport SEXP CMF_p_updatePseudoData(SEXP XmSEXP, SEXP U1mSEXP, SEXP U2mSEXP, SEXP RvSEXP, SEXP CvSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xm(XmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type U1m(U1mSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type U2m(U2mSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Rv(RvSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Cv(CvSEXP );
        p_updatePseudoData(Xm, U1m, U2m, Rv, Cv);
    }
    return R_NilValue;
END_RCPP
}
// p_updateTau
NumericVector p_updateTau(NumericMatrix Xm, NumericMatrix U1m, NumericMatrix U2m, NumericMatrix cov1m, NumericMatrix cov2m, NumericVector Rv, NumericVector Cv, NumericVector nu1v, NumericVector nu2v);
RcppExport SEXP CMF_p_updateTau(SEXP XmSEXP, SEXP U1mSEXP, SEXP U2mSEXP, SEXP cov1mSEXP, SEXP cov2mSEXP, SEXP RvSEXP, SEXP CvSEXP, SEXP nu1vSEXP, SEXP nu2vSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xm(XmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type U1m(U1mSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type U2m(U2mSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type cov1m(cov1mSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type cov2m(cov2mSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Rv(RvSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Cv(CvSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu1v(nu1vSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu2v(nu2vSEXP );
        NumericVector __result = p_updateTau(Xm, U1m, U2m, cov1m, cov2m, Rv, Cv, nu1v, nu2v);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// p_updateMean
List p_updateMean(NumericMatrix Xm, NumericMatrix U1m, NumericMatrix U2m, NumericVector Mv, NumericVector I);
RcppExport SEXP CMF_p_updateMean(SEXP XmSEXP, SEXP U1mSEXP, SEXP U2mSEXP, SEXP MvSEXP, SEXP ISEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xm(XmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type U1m(U1mSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type U2m(U2mSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type Mv(MvSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type I(ISEXP );
        List __result = p_updateMean(Xm, U1m, U2m, Mv, I);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// p_covUsparse
void p_covUsparse(NumericMatrix Xm, NumericMatrix Cm, NumericMatrix OUm, NumericMatrix OCm, NumericVector I, NumericVector T);
RcppExport SEXP CMF_p_covUsparse(SEXP XmSEXP, SEXP CmSEXP, SEXP OUmSEXP, SEXP OCmSEXP, SEXP ISEXP, SEXP TSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xm(XmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type Cm(CmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type OUm(OUmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type OCm(OCmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type I(ISEXP );
        Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP );
        p_covUsparse(Xm, Cm, OUm, OCm, I, T);
    }
    return R_NilValue;
END_RCPP
}
